version: '3'
services:

  nginx:
    image: nginx:latest
    build:
      context: ./ngnix
      dockerfile: Dockerfile
    container_name: nginx
    restart: on-failure
    depends_on:
      - back-end
      - front-end
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:11
    restart: on-failure
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=568698
      - POSTGRES_DB=freelance
      - PGDATA=/tmp
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  flyway:
    image: boxfuse/flyway
    container_name: flyway
    restart: on-failure
    command: -url=jdbc:postgresql://db:5432/freelance -schemas=freelance -user=postgres -password=568698 -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - db

  back-end:
    container_name: back-end
    restart: on-failure
    links:
      - db
    ports:
      - 8282:8282
    build:
      context: ./back-end
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./back-end/target/back-end-0.0.1.jar

  front-end:
    container_name: front-end
    restart: on-failure
    links:
      - back-end
    ports:
      - 8181:8181
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./front-end/target/front-end-0.0.1.jar