##Don't forget to change credentials(user,pwd)

# Spring Boot configuration
spring:
  profiles:
    active: development
 # Database
  datasource:
    url: jdbc:postgresql://172.30.96.133:5432/freelance #change to your local db name
    username: postgres
    password: qwerty

  flyway:
    url: jdbc:postgresql://172.30.96.133:5432/freelance
    schemas: freelance
    user: postgres
    password: qwerty

# JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080

